### ISSUE TITLE
Palace Peaks: Button used to open the gates for an emblem doesn't work

### ISSUE THREAD

**Issue by TBlazerSRB2** [TehRealSalt/sugoi#2]
To get an emblem behind this gate, a switch needs to be pressed down. I think the button to open it is the one in this room but it's not working.

![srb20027](https://github.com/TehRealSalt/sugoi/assets/170482704/7165104f-f746-4339-a30d-db2344db2462)

**Comment by TehRealSalt** [comment]
This has a different solution -- closing for now
