### ISSUE TITLE
After getting all 7 Emeralds, Tokens are no longer stored when collected in the field

### ISSUE THREAD

**Issue by TBlazerSRB2** [TehRealSalt/sugoi#3]
on SUBARASHII and later, you could still collect Emerald Tokens even when you had all 7 emeralds so you could still purchase items from the shop. Collecting one now just gives you 50 rings but doesn't increment your token counter anymore.

**Comment by TehRealSalt** [comment]
I am not able to replicate with just SUGOI loaded. More detail?

**Comment by TBlazerSRB2** [comment]
Looks to just be a conflict with how Adventure Sonic treated Emerald Tokens after getting all the emeralds. Vanilla characters can pick up tokens just fine. Closing.
